on:
  push:
    branches:
      - master
      - main
    paths:
      - 'surrealdb/**'
  pull_request:
    paths:
      - 'surrealdb/**'
name: "Tests SurrealDB"
jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - 1.22.x
          - 1.23.x
          - 1.24.x
    services:
      surrealdb:
        image: 'surrealdb/surrealdb:latest'
        ports:
          - '8000:8000'
        command: [ "start", "--user", "root", "--pass", "root" ]
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '${{ matrix.go-version }}'

      - name: Wait for SurrealDB
        run: |
          for i in {1..15}; do
            nc -z localhost 8000 && echo "SurrealDB is up!" && break
            echo "Waiting for SurrealDB..."
            sleep 2
          done
      - name: Run Test
        run: cd ./surrealdb && go test ./... -v -race
